name: 'Install Toolchain'
description: 'Install UCRT toolchain to build R/R packages'
inputs:
  ucrt3-release:
    description: 'release tag for UCRT3'
    required: false
    default: 'v0.2'
  toolchain-type:
    description: 'none/base/full toolchain'
    required: false
    default: none
runs:
  using: 'composite'
  steps:
   - name: Install toolchain
     run: |
       TYPE="${{ inputs.toolchain-type }}"
       TDIR="~/x86_64-w64-mingw32.static.posix"
       if [ "${{ runner.os }}" = Windows -a $TYPE != "none" -a -r $TDIR/type ] ; then
           if [ "`cat $TDIR/type`" != "$TYPE" ] ; then
             # delete non-matching toolchain
             rm -rf $TDIR
           else
             # prepared for caching
             echo "Re-using cached toolchain."
           fi
       fi
       
       if [ "${{ runner.os }}" = Windows -a $TYPE != "none" \
            -a ! -d $TDIR ] ; then
       
         echo "::group::Downloading and installing the toolchain"
         TAG="${{ inputs.ucrt3-release }}"
         if [ $TYPE = "base" ] ; then
           SUFF="_base"
         else
           SUFF=""
         fi
         URL=`curl -s https://api.github.com/repos/kalibera/ucrt3/releases | \
           sed -n 's!^ *\"*browser_download_url\"*: \"\(.*/download/'$TAG'/gcc10_ucrt3'${SUFF}'_[0-9]\+\.txz\)\"!\1!p'`
         curl -s -L $URL > toolchain.txz
         if [ ! -r toolchain.txz ] ; then
           echo "::error ::ERROR: failed to download toolchain"
         fi
         ls -l toolchain.txz
         tar xf toolchain.txz -C ~
         echo "Home dir"
         ls -lrth ~/
         echo "Toolchain dir"
         ls -lrth $TDIR
         echo "Toolchain dir 2"
         ls -lrth ~/x86_64-w64-mingw32.static.posix
         echo "Current directory is `pwd`"
         if [ ! -d $TDIR ] ; then
           echo "::error ::ERROR: failed to install toolchain"
         fi
         echo "$TYPE" > $TDIR/type
         echo "::endgroup::"
       fi
     shell: bash
       
   - name: Set up environment for R
     run: |
       TDIR="~/x86_64-w64-mingw32.static.posix"
       if [ "${{ runner.os }}" = Windows ] ; then
         echo "::group::Setting up environment for R"
         # echo "c:/msys64/usr/bin" >> $GITHUB_PATH
         echo "$TDIR/bin" >> $GITHUB_PATH
         # echo "MSYSTEM=MSYS" >> $GITHUB_ENV
         echo "::endgroup::'"
       fi
     shell: bash
